### DISCUSSION TITLE
Data Persistence on Solr in Cloud mode (SolrCloud)

### DISCUSSION THREAD

**Discussion by samuelrac** [docker-solr/docker-solr#386] [Q&A] [answered]
Hello community, how are you?

I am currently having problems with Solr to keep your Core/Collections data saved to disk.

I created a repository to share robust Solr configurations in Cloud mode: https://github.com/samuelrac/solr-cloud and little by little I'm leaving the SolrCloud configuration more complete and robust for simply those who want to use in development or production of a application just have to download and that's it, because I feel a great lack of this type of content about Solr that has a very complete documentation, but complex.

My intention is to facilitate.

But when I run docker-compose I access Solr I create the collection, insert data and for some reason the host machine restarts or the container restarts, all the data and the previously created collection are lost, and as you can see in the docker-compose configuration. yml I persist the data in the correct folders where the Solr and ZooKeeper indexes and collections data are stored.

## docker-compose.yml

```
version: '3'

services:

  solr1:
    container_name: solr1
    image: samuelrac/solr:8.8.2
    restart: always
    volumes:
      - solr_data:/var/solr/data
    ports:
     - "8981:8983"
    environment:
      - SOLR_AUTH_TYPE=basic
      - ZK_HOST=zk1:2181,zk2:2181,zk3:2181
    networks:
      - solr
    depends_on:
      - zk1
      - zk2
      - zk3

  solr2:
    container_name: solr2
    image: samuelrac/solr:8.8.2
    restart: always
    volumes:
      - solr_data:/var/solr/data
    ports:
     - "8982:8983"
    environment:
      - SOLR_AUTH_TYPE=basic
      - ZK_HOST=zk1:2181,zk2:2181,zk3:2181
    networks:
      - solr
    depends_on:
      - zk1
      - zk2
      - zk3

  solr3:
    container_name: solr3
    image: samuelrac/solr:8.8.2
    restart: always
    volumes:
      - solr_data:/var/solr/data
    ports:
     - "8983:8983"
    environment:
      - SOLR_AUTH_TYPE=basic
      - ZK_HOST=zk1:2181,zk2:2181,zk3:2181
    networks:
      - solr
    depends_on:
      - zk1
      - zk2
      - zk3

  zk1:
    image: zookeeper:3.7.0
    restart: always
    container_name: zk1
    hostname: zk1
    ports:
      - 2181:2181
      - 7001:7000
    volumes:
      - zookeeper_data:/data
      - zookeeper_wd:/apache-zookeeper-3.7.0-bin
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr
  
....

  zk2:
    image: zookeeper:3.7.0
    restart: always
    container_name: zk2
    hostname: zk2
    ports:
      - 2182:2181
      - 7002:7000
    volumes:
      - zookeeper_data:/data
      - zookeeper_wd:/apache-zookeeper-3.7.0-bin
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

....

  zk3:
    image: zookeeper:3.7.0
    restart: always
    container_name: zk3
    hostname: zk3
    ports:
      - 2183:2181
      - 7003:7000
    volumes:
      - zookeeper_data:/data
      - zookeeper_wd:/apache-zookeeper-3.7.0-bin
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

....

volumes:
  solr_data:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper_wd:
    driver: local

networks:
  solr:
```

## Dockerfile

```
FROM solr:8.8.2

WORKDIR /var/solr/data

COPY ./files/solr.in.sh /etc/default/solr.in.sh
COPY ./files/security.json /var/solr/data/security.json
COPY ./files/zoo.cfg /var/solr/data/zoo.cfg
```

Note: I'm running docker-compose in Swarm mode, using 1 leader and 2 nodes.

Can you help me?
