### ISSUE TITLE
Solr + multi-core + volume mounting wipes index

### ISSUE THREAD

**Issue by sylus** [docker-solr/docker-solr#101]
Hi there! 

First off wanted to say again thanks for the amazing work! There really is no better tool to develop with.

My issue is I have 10 solr cores that were exported and I wanted them to be leveraged by the solr container through volume mounting and am unsure how to to go about this.

Here is a picture of my cores:

<img width="307" alt="solr_cores" src="https://cloud.githubusercontent.com/assets/984304/22373777/570b344e-e471-11e6-8a7a-d66288333682.png">

Here is my docker-compose.yml snippet:

```yml
solr:
   image: solr:6.3-alpine
   hostname: solr
   ports:
     - "8983:8983"
     - "10616:10616"
   volumes:
     - ./docker/conf/solr/drupal:/opt/solr/server/solr/configsets/drupal/conf
     - ./vendor/open-data/ckanext-canada/conf/solr:/tmp/solr/ckan
     - ./docker/conf/solr/scripts/create-cores:/docker-entrypoint-initdb.d/create_cores.sh
     - ./docker/solr_data:/tmp/ckan
   container_name: siteopendata_solr
```

Here is my create-cores script:

```sh
#!/bin/sh
source /opt/docker-solr/scripts/docker-entrypoint.sh

CONFIG_ROOT=/opt/solr/server/solr/configsets
CKAN_CONFIG=$CONFIG_ROOT/ckan
CONFIG_SOURCE=$CONFIG_ROOT/data_driven_schema_configs

mkdir -p /opt/solr/server/solr/ckan
cp /opt/solr/server/solr/solr.xml /opt/solr/server/solr/ckan
export SOLR_HOME=/opt/solr/server/solr/ckan

initial_solr_begin

# Creates the default Drupal Core
# /opt/solr/bin/solr create -c drupal -d $CONFIG_ROOT/drupal

#Prepare ckan config
mkdir -p $CKAN_CONFIG/conf
cp -r $CONFIG_SOURCE/. $CKAN_CONFIG
cp /tmp/solr/ckan/schema.ati_pd.xml $CKAN_CONFIG/conf

declare -a cores=(
  'core_info'
  'core_maps'
  'core_travelq'
  'core_hospitalityq'
  'core_grants'
  'core_contracts'
  'core_contractsa'
  'core_travela'
  'core_hospitalitya'
  'core_reclassification'
  'core_wrongdoing'
);

for core in "${cores[@]}"
do
    if [[ ! -d /opt/solr/server/solr/core_grants ]]; then
      /opt/solr/bin/solr create -c $core -d /tmp/ckan/"${core}"
    fi
done

initial_solr_end
```

By calling the solr/create function it always wipes the index forcing me to re-copy the index back to the core path. I was wondering if perhaps am going about this the wrong way? In essence I have all of the cores + conf + data outside the container and I would just like to volume mount them all.
