### ISSUE TITLE
Impossible to name a core with docker-compose file

### ISSUE THREAD

**Issue by rudkov** [docker-solr/docker-solr#102]
I am trying to create new core with custom name (different from `gettingstarted` one). I use docker-compose file with the following settings:

```
version: '2'

services:
  solr:
    image: solr
    ports:
      - '8983:8983'
    volumes:
      - solr-data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - test_core_name

volumes:
  solr-data:
    external: true
```

When I run `docker-compose up solr` for the first time I see the following log:
```
solr_1   | Executing /opt/docker-solr/scripts/solr-precreate test_core_name
solr_1   | created gettingstarted
```
Another time I restart this container I see following:
```
solr_1   | Executing /opt/docker-solr/scripts/solr-precreate test_core_name
solr_1   | core gettingstarted already exists
```

Am I doing something wrong? It seems to me that it is not working as expected.

**Comment by makuk66** [comment]
I think this is known bug we should hopefully see fixed soon.
In the meantime, try:

```
version: '2'
services:
  solr:
    image: dockersolr/docker-solr
    ports:
      - "8983:8983"
    entrypoint:
      - solr-precreate
      - test_core_name
```
