### ISSUE TITLE
Custom Schema

### ISSUE THREAD

**Issue by kalinchuk** [docker-solr/docker-solr#111]
Is there any way to use a custom schema using `docker-compose`?

**Comment by makuk66** [comment]
Yes. Just pre-create your collection, with whatever configuration you like, before starting solr. 
You can pre-create your collection into a named volume or host-mounted directory (into mycores, or by replacing the whole SOLR_HOME), using manual commands, and then reference that in your docker-compose.yml. Or you can write a script, mount that into your container, and run it, creating and configuring the collection on the fly before running Solr.

An example of pre-creating the collection and using SOLR_HOME.
First we copy the SOLR_HOME directory to our local filesystem:

```console
$ mkdir mysolrhome
$ sudo chown 8983:8983 mysolrhome
$ docker run --rm -v $PWD/mysolrhome:/mysolrhome solr \
  bash -c "cp -R /opt/solr/server/solr/* /mysolrhome"
$ sudo chown -R $USER mysolrhome
```

Next we will create our core, and modify its configuration. You can use a text editor, but I'll use sed to comment-out the `_text_` field definition.

```console
$ cp -r mysolrhome/configsets/data_driven_schema_configs mysolrhome/gettingstarted
$ touch mysolrhome/gettingstarted/core.properties
$ sed -E -i -e 's,(<field name="_text_" type="text_general" indexed="true" stored="false" multiValued="true"/>),<!-- \1 -->,' \
    -e 's,(<copyField source="\*" dest="_text_"/>),<!-- \1 -->,' \
    mysolrhome/gettingstarted/conf/managed-schema
$ sudo chown -R 8983:8983 mysolrhome
```

Now your core is ready, and you can use it with docker-compose like:

```yaml
version: '3'
services:
  solr:
    image: solr
    command: ["solr", "-f"]
    environment:
    - SOLR_HOME=/mysolrhome
    ports:
     - "8983:8983"
    volumes:
      - "./mysolrhome:/mysolrhome"
```


An example of the script approach:

With a `myscript.sh` like:

```bash
#!/bin/bash
set -e

if [[ "$VERBOSE" = "yes" ]]; then
    set -x
fi
sentinel=/opt/docker-solr/collection_created
if [ -f $sentinel ]; then
  echo "collection already exists"
else
  mkdir -p /mysolrhome
  cp -r /opt/solr/server/solr/* /mysolrhome
  cp -r /mysolrhome/configsets/data_driven_schema_configs /mysolrhome/gettingstarted
  touch /mysolrhome/gettingstarted/core.properties
  sed -E -i -e 's,(<field name="_text_" type="text_general" indexed="true" stored="false" multiValued="true"/>),<!-- \1 -->,' \
    -e 's,(<copyField source="\*" dest="_text_"/>),<!-- \1 -->,' \
    /mysolrhome/gettingstarted/conf/managed-schema
  touch $sentinel
fi
exec solr -f
```

You can run:

```yaml
version: '3'
services:
  solr:
    image: solr
    command: ["bash", "/myscript.sh"]
    ports:
     - "8983:8983"
    volumes:
      - "./myscript.sh:/myscript.sh"
```

In both examples there is a little preparation that needs to happen before running docker-compose. If you want to avoid that you would have to come up with a way to get your config changes and scripts onto the container, like curl the script from somewhere, or create a custom solr image or some such.

Instead of modifying the config file directly like in these examples, you could use the schema API from your script.
