### ISSUE TITLE
SolrCloud on Docker Swarm : SOLR_PORT environment variable issue

### ISSUE THREAD

**Issue by si-harps** [docker-solr/docker-solr#124]
I'm currently experiencing an issue whilst attempting to start a SolrCloud cluster using Docker Swarm on AWS.

When I run the same configuration on 3 local VMs I am able to set the SOLR_PORT environment variable in docker-compose.yml. This starts each instance on the required port (i'm using 8081, 8082, 8083 for example).

After deployment to AWS via Docker cloud, each Solr instance starts on port 8983. It seems to ignore the environment variable although it does appear to be set as expected.

Here is some info that might be useful for debugging...

1. Logs from one of the affected containers...

![docker_logs_solr1](https://user-images.githubusercontent.com/2602859/29210365-3217afd2-7e8b-11e7-9228-ed4f222909ab.png)

...line 3 shows Solr starting in cloud mode on port 8983.

2. Echo SOLR_PORT env on the same container...

![docker_exec_solr](https://user-images.githubusercontent.com/2602859/29210131-e05ef700-7e89-11e7-8ed1-e4e50980bf10.png)

Please see below for current docker-compose file being used to deploy the stack (ignore commented lines - still WIP)...

```
version: '3'
services:
    zoo-1:
        image: zookeeper
        ports:
            - "2181:2181"
        networks:
            - zoonet
        # volumes:
        #     - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo-2:2888:3888 server.3=zoo-3:2888:3888
            # ZOO_LOG_DIR: /opt/persist/logs
            # ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            replicas: 1
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == [MY_AWS_HOSTNAME]]
    zoo-2:
        image: zookeeper
        ports:
            - "2182:2182"
        networks:
            - zoonet
        # volumes:
        #     - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 2
            ZOO_PORT: 2182
            ZOO_SERVERS: server.1=zoo-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo-3:2888:3888
            # ZOO_LOG_DIR: /opt/persist/logs
            # ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == [MY_AWS_HOSTNAME]]
    zoo-3:
        image: zookeeper
        ports:
            - "2183:2183"
        networks:
            - zoonet
        # volumes:
        #     - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 3
            ZOO_PORT: 2183
            ZOO_SERVERS: server.1=zoo-1:2888:3888 server.2=zoo-2:2888:3888 server.3=0.0.0.0:2888:3888
            # ZOO_LOG_DIR: /opt/persist/logs
            # ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == [MY_AWS_HOSTNAME]]
    solr-1:
        image: solr
        ports:
            - 8081:8081
        networks:
            - zoonet
        # volumes:
        #     - ./opt/solr/logs:/opt/logs
        #     - ./opt/solr/store:/store
        #     - ./opt/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            SOLR_PORT: 8081
            # SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            # SOLR_LOGS_DIR: /opt/logs
            SOLR_HOST: solr-1
            SOLR_HEAP:
            SOLR_JAVA_MEM:
        depends_on:
            - zoo-1
            - zoo-2
            - zoo-3
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == [MY_AWS_HOSTNAME]]
    solr-2:
        image: solr
        ports:
            - 8082:8082
        networks:
            - zoonet
        # volumes:
        #     - ./opt/solr/logs:/opt/logs
        #     - ./opt/solr/store:/store
        #     - ./opt/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            SOLR_PORT: 8082
            # SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            # SOLR_LOGS_DIR: /opt/logs
            SOLR_HOST: solr-2
            SOLR_HEAP:
            SOLR_JAVA_MEM:
        depends_on:
            - zoo-1
            - zoo-2
            - zoo-3
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == [MY_AWS_HOSTNAME]]
    solr-3:
        image: solr
        ports:
            - 8083:8083
        networks:
            - zoonet
        # volumes:
        #     - ./opt/solr/logs:/opt/logs
        #     - ./opt/solr/store:/store
        #     - ./opt/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            SOLR_PORT: 8083
            # SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            # SOLR_LOGS_DIR: /opt/logs
            SOLR_HOST: solr-3
            SOLR_HEAP:
            SOLR_JAVA_MEM:
        depends_on:
            - zoo-1
            - zoo-2
            - zoo-3
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == [MY_AWS_HOSTNAME]]
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - zoonet
networks:
    zoonet:
        # driver: overlay
        # ipam:
        #     driver: default
        #     config:
        #         - subnet: 10.101.0.0/16
```

Please let me know if there is any further info you need to investigate. Many thanks in advance for your help
