### ISSUE TITLE
Solr + multi-core + volume mounting wipes index

### ISSUE THREAD

**Issue by bober2000** [docker-solr/docker-solr#125]
Hi. Could you please help me?
The problem is the same as in #101 
My `docker-compose.yml` file:
```
version: "2"
services:
solr:
      build:
         dockerfile: ./docker/solr/Dockerfile
         context: .
      volumes:
        - /opt/docker/mycores:/opt/solr/server/solr/mycores
```
File `docker/solr/Dockerfile`
```
FROM solr:6.6-alpine
USER root
RUN chown -R solr:solr /opt/solr/server/solr/
USER solr
```
directory `/opt/docker/mycores` contains my cores with conf and data dirs inside. I'm expecting that after restart my indexes in `mycores/core_name/data/index` dir will be available at host system but as I see - it creates indexes in `server/solr/core_name/index` so after container restart I have to re-index again.

**Comment by makuk66** [comment]
From your description I can't tell why it's not working; you didn't say how/when you create the core.
Did you perhaps forget to create a `core.properties` file?



There are various ways you can deal with preparing things for your Docker-compose.
You can manually prepare your cores (which sounds like what you're trying to do), which
can look like this:

First, create your core, chown it to solr, and create a core by copying config and creating a core.properties:

```
$ mkdir mycores
$ docker run --user root -v $PWD/mycores:/opt/solr/server/solr/mycores solr:6.6 /bin/chown -R solr:solr /opt/solr/server/solr/
$ docker run -v "$PWD/mycores:/opt/solr/server/solr/mycores" solr:6.6 /bin/cp -r /opt/solr/server/solr/configsets/data_driven_schema_configs /opt/solr/server/solr/mycores/core1
$ docker run -v "$PWD/mycores:/opt/solr/server/solr/mycores" solr:6.6 bash -c 'echo name=core1 > /opt/solr/server/solr/mycores/core1/core.properties'
``` 
At this point you have a `mycores/core1` directory visible on the host.
Now in your docker compose, there is no need for the custom Dockerfile; just use solr.
For example, for docker-compose 1.15.0:

```
version: "3.2"
services:
  solr:
    image: solr:6.2
    volumes:
      - type: bind
        source: /home/mak/docker-solr/issue125/mycores
        target: /opt/solr/server/solr/mycores
    ports:
    - "8983:8983"
```

Then `docker-compose up`

will show you:

```
solr_1  | 2017-08-16 09:58:48.757 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 1 core definitions underneath /opt/solr/server/solr
solr_1  | 2017-08-16 09:58:48.758 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Cores are: [core1]
```

If you then add docs: 

```
docker exec -it issue125_solr_1 post -c core1 example/exampledocs/manufacturers.xml
```

you'll see them in Solr. If you then `docker-compose down` and `docker-compose up`, they will still be there.


A simpler approach would be to let docker-solr do some of the work for you:

```
$ rm -fr mycores
$ mkdir mycores
$ docker run --user root -v $PWD/mycores:/opt/solr/server/solr/mycores solr:6.6 /bin/chown -R solr:solr /opt/solr/server/solr/
```

Then with this `docker-compose.yml`:

```
version: "3.2"
services:
  solr:
    image: solr:6.6
    volumes:
      - type: bind
        source: /home/mak/docker-solr/issue125/mycores
        target: /opt/solr/server/solr/mycores
    ports:
    - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - core1
```

a `docker-compose up` will create the core for you. 
If you then `docker-compose down`, and re-run `docker-compose up` it will find the existing core, and not re-create it, and thus will retain your docs.
