### ISSUE TITLE
error when trying create cores with docker compose

### ISSUE THREAD

**Issue by drizzef** [docker-solr/docker-solr#129]
Hi, 
firstly, amazing job! i just pick SOLR as a search engine for big CSV files and i want to create 2 cores and index immediately the csv files.

i create this docker-compose.yml file:
```
version: '2'
services:
  solr:
    image: weed_solr
    ports:
      - "8983:8983"
    volumes:
      - ./services/solr/data:/opt/solr/server/solr
    entrypoint:
      - solr-precreate
      - yyy
```

Also the Dockerfile:
```
FROM solr:6
EXPOSE 8983

COPY services/solr/scripts /opt/xxx_solr/scripts
VOLUME services/solr/data /opt/solr/server/solr

USER root
RUN chown -R $SOLR_USER:$SOLR_USER /opt/xxx_solr/; 
USER $SOLR_USER
RUN mkdir /opt/solr/server/solr/yyy
```

when i run docker-compose.yml i get the following error:
`cp: cannot stat '/opt/solr/server/solr/configsets/data_driven_schema_configs/': No such file or directory`
 
something i did wrong?

thanks!
