### ISSUE TITLE
How to achieve autoscaling of solr service

### ISSUE THREAD

**Issue by sugun999** [docker-solr/docker-solr#151]
Hi,

I have setup solrcloud with below docker compose file.
After that I created collection called "test" with 1 shard and 2 replicationfactor.

Now I would like to scale solr service based on usage load automatically. So that new solr instances will act as replicas and can share read requests load.
I tried with "docker service scale solr=3" but new task/service-instance doesn't get created with my "test" collection.

How can I get this working? Appreciated any help.

```
version: "3"

networks:
  solr_network:
    external: true

volumes:
  solr:

services:
  solr:
    image: solr:6.6.0
    networks:
      - solr_network
    ports:
      - "8983:8983"
    command: /opt/solr/bin/solr start -f -z zookeeper:2181
    volumes:
      - solr:/opt/solr/server/solr
    environment:
      SOLR_HEAP: 2G
    depends_on:
      - zookeeper
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '1'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 3G
```
Thanks.
