### ISSUE TITLE
create multiple cores through docker-compose

### ISSUE THREAD

**Issue by jmanuelortiz** [docker-solr/docker-solr#188]
Hi
Is there a way to pass multiple cores on the docker-compose file?

REgards

Manuel

**Comment by makuk66** [comment]
The simplest way would to just run:
```
docker run -p 8983:8983  --rm -it solr \
  bash -c "precreate-core core1; precreate-core core2; exec solr -f"
```
Or expressed as a `docker-compose.yml`:
```
version: '3'
services:
  solr:
    image: "solr"
    entrypoint:
    - bash
    - "-c"
    - "precreate-core core1; precreate-core core2; exec solr -f"
    ports:
     - "8983:8983"
```
Alternative approaches are putting that into a script, mounting that in and running that.
Or you can bring solr up in one service, then create the cores from another, but that'd be more involved.
