### ISSUE TITLE
SOLR_HEAP or SOLR_JAVA_MEM set in solr.in.sh ignored

### ISSUE THREAD

**Issue by int8** [docker-solr/docker-solr#229]
Hi there, 

I have the following `docker-compose.yml`: 

```
version: '2'
services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/cores
      - "/my/local/path/to/solr.in.sh:/opt/solr/bin/solr.in.sh"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - corename
volumes:
  data:
```

+ `solr.in.sh` on host has this line
```
SOLR_JAVA_MEM="-Xms4096m -Xmx4096m"
```
uncommented and changed (alternatively I tried uncommenting `SOLR_HEAP` using up to `16G`)

When I create container with `docker-compose up` I can see the following lines in logs:

```
solr_1  | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1  | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
solr_1  | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
```

+  `docker stats` on my solr container gives: 

```
CONTAINER ID        NAME                   CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
6a261708fb40        search-engine_solr_1   0.68%               461.6MiB / 62.86GiB   0.72%               4.62kB / 0B         0B / 81.9kB         56
```

and finally when I try to index 2GB file I get `java.lang.OutOfMemoryError: Java heap space`

What do I do wrong?
