### ISSUE TITLE
Start Solr in Cloudmode and create a collection

### ISSUE THREAD

**Issue by Max-Leopold** [docker-solr/docker-solr#244]
Hey,

Is it possible to run Solr in Cloud mode through docker-compose and create a collection at startup?
In console this is working for me:
`bash -c "bin/solr start -c; bin/solr create_collection -c collection1"`

But in a docker-compose somthing like this:
```
solr:
    image: solr:latest
    ports:
      - "8983:8983"
    volumes:
      - solr:/var/lib/solr/data
    restart: always
    entrypoint:
      - bash
      - "-c"
      - "exec solr -c -f; exec solr create_collection -c collection1;"
```
doesnt work for me.

**Comment by makuk66** [comment]
```
bash -c "bin/solr start -c; bin/solr create_collection -c collection1"
```
What that does is run Solr, in cloud mode, in the background, then creates a collection.
If you were doing that from docker compose, that would happen, and then your shell would run out of commands to execute, exit, and the container would exit. So you can't just do that. You want to be running Solr in the foreground.

```
    entrypoint:
      - bash
      - "-c"
      - "exec solr -c -f; exec solr create_collection -c collection1;"
```
When you `exec solr -c -f`, you're replacing your shell with `solr -c -f`, so Solr starts running (in the foreground), and you never get to the other commands, so your collection never gets created. When you see `exec` in the docker-solr scripts, it is always when the last command runs solr; that way solr ends up replacing your shell, and runs as process 1 (or directly under tiny, if you use that).

If you removed the `exec`s, you'd get the same behaviour as your first command, but as explained, that won't do what you expect either.

When you don't run in cloud mode, docker-solr provides scripts to deal with this in different ways: `solr-create` runs solr in the background, creates the collection, the stops solr and starts it in the foreground. Whereas `solr-precreate` creates the collection on disk, then runs solr in the foreground. But, these don't work with cloud mode, as [reported previously](https://github.com/docker-solr/docker-solr/issues/183).

There was an experimental PR https://github.com/docker-solr/docker-solr/pull/186 to have `solr-create` work in cloud mode, but at a cost of a bunch of complexity and unwanted feature coupling, and it's now well out of date. An alternative, and arguably better, approach would be to start an additional container whose whose job it is to create the collection remotely. We should have a documented example for that, but currently we don't. You could have a go at that though. For applications that talk to Solr, it may make sense for that application itself to create the required collection when the app starts up. I don't think there is an equivalent to `solr-precreate` in Solr itself for it to create a collection in cloud mode at startup, though I'd love to be corrected on that. And another alternative, which I wouldn't recommend, is you could before running Solr in the foreground, start a script in the background to wait for Solr to be ready and create the collections. The problem there is that any errors won't appear in you `docker logs`.

**Comment by makuk66** [comment]
> An alternative, and arguably better, approach would be to start an additional container whose whose job it is to create the collection remotely. We should have a documented example for that, but currently we don't. 

Something like this: https://gist.github.com/makuk66/0812f70b77aa92230c203cec41acac64#file-docker-compose-yml-L64

**Comment by Max-Leopold** [comment]
So, first of all, thank you for your excellent service in this repo. You always answer really quick and give examples as solutions.

Second of all:
I now did something pretty similar, I post it here for reference, if somebody has a similar problem.

First I created a python script that looks if the collection already exists and if not creates it:

```
import http.client
import json

payload = ""

conn = http.client.HTTPConnection("solr:8983")

conn.request("GET", "/solr/admin/collections?action=LIST&wt=json", payload)

res = conn.getresponse()
data = res.read()
parsed_json = (json.loads(data))

# Check if collection is already present
if 'mentions' not in parsed_json['collections']:
    # Create collection if not present
    conn.request("GET", "/solr/admin/collections?action=CREATE&name=mentions&numShards=1&replicationFactor=1", payload)

    res = conn.getresponse()
    data = res.read()

    print(json.dumps(json.loads(data), indent=4, sort_keys=True))
else:
    print("Collection already present")
```

This does pretty much the same, then the `curl` in your example.
Then I created a Dockerfile:

```
FROM python:3
ADD create-collection.py /create-collection.py
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait
RUN chmod +x /wait
CMD /wait &&python /create-collection.py
```

I used this library (https://github.com/ufoscout/docker-compose-wait) to let the application wait until solr is started up. Not the most elegant way, but I don't know any other way.

The last thing I did was creating the docker-compose:

```
version: '3'

services:

  solr:
    image: solr
    hostname: solr
    ports:
      - "8983:8983"
    entrypoint:
      - bash
      - "-c"
      - "exec solr -c -f"


  create-collection:
    build: .
    hostname: create-collection
    environment:
      WAIT_HOSTS: solr:8983
      WAIT_HOSTS_TIMEOUT: 60

volumes:
  solr:
```

The create-collection container is the container that waits until solr is started and then create a collection in it. In my case the collection I want to create is called 'mentions'.

**Comment by makuk66** [comment]
> I now did something pretty similar, I post it here for reference, if somebody has a similar problem.

Thanks! Yup, many ways to skin this cat.

```
    entrypoint:
      - bash
      - "-c"
      - "exec solr -c -f"
```

You don't need bash here; you can just run solr with those arguments. We use `bash -c` only when you need to run multiple commands.

> This does pretty much the same, then the curl in your example.

If you don't like the curl command, you can get the Solr CLI to create the collection:

```
  create-collection:
    image: solr:8.2
    container_name: create-collection
    networks:
      - solr
    command:
      - bash
      - "-c"
      - "sleep 5; wait-for-solr.sh --max-attempts 10 --wait-seconds 5 --solr-url http://solr1:8983/; SOLR_HOST=solr1 solr create_collection -c col3 -p 8983"
```

It's bit ugly having to specify `SOLR_HOST` this way, rather than say having a `-h` parameter, but it works. Per https://github.com/apache/lucene-solr/blob/master/solr/bin/solr#L492 it sounds like this command can also be used to upload your custom config.

> I used this library (https://github.com/ufoscout/docker-compose-wait) to let the application wait until solr is started up. Not the most elegant way, but I don't know any other way.

docker-solr comes with [wait-for-solr.sh](https://github.com/docker-solr/docker-solr/blob/master/scripts/wait-for-solr.sh) as used here https://gist.github.com/makuk66/0812f70b77aa92230c203cec41acac64#file-docker-compose-yml-L72, so you could just download that and ADD it to your create-collection image instead of docker-compose-wait; that's what I would do. Alternatively, docker-solr's base image includes python 2.7, so you could run your `create-collection.py` script from a docker-solr container (you might need to change some things for 2.7, not sure). Alternatively, given that all that docker-compose-wait does is wait for a socket, you could implement that functionality in your python script.
