### ISSUE TITLE
INIT_SOLR_HOME not working with 8.2

### ISSUE THREAD

**Issue by Mizar01** [docker-solr/docker-solr#245]
I used docker compose to run the container.
```
version: '2'
services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - ./home:/opt/solr_custom_home
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - testcore1
    environment:
      - SOLR_HOME=/opt/solr_custom_home
      - INIT_SOLR_HOME=yes
```

Everything is fine, except that INIT_SOLR_HOME=yes has no effect, and solr fails to start with the error:
`Solr home directory /opt/solr_custom_home must contain a solr.xml file!`

Is INIT_SOLR_HOME variable supported in v.8.2?
I noted that in the git repository there's no init_solr_home.sh script anymore for 8+.

**Comment by Mizar01** [comment]
I found myself this post:
https://github.com/docker-solr/docker-solr/pull/210

INIT_SOLR_HOME is no longer supported in 8+ versions. 

The docker documentation should mention that.

The solution seems to be to mount an empty volume in /var/solr. I will try it.

**Comment by stefanocog** [comment]
Thanks, but i get an error also mounting /var/solr, this my compose:

```
version: '3'
services:
  solr:
    image: solr:8.2.0
    ports:
      - "8983:8983"
    volumes:
      - ./cores:/var/solr
    entrypoint:
      - bash
      - "-c"
      - "precreate-core mycore; exec solr -f"
```
Into logs i have:
```
Executing /opt/docker-solr/scripts/precreate-core mycore
cp: cannot create directory '/var/solr/data/mycore': No such file or directory

Solr home directory /var/solr/data not found!
```
How you have resolved?

Thanks!

**Comment by Mizar01** [comment]
I don't know if this is related to the different entrypoint setting. The script I specified maybe is going to do all the settings you need. Also, I'm using solr:latest for now (I'm testing it).

My working example is:
`version: '2'
services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - ./home:/var/solr      #Solar inizializza i file di conf. qui, se non esistono.
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - testcore1`

**Comment by qeepcologne** [comment]
did you tried to create a volume for /var/solr/data instead of /var/solr and also check the directory owner and chmod? e.g. i have the following volumes:
      - /opt/staging/solr/data:/var/solr/data
      - /opt/staging/solr/logs:/var/log/solr
      - /opt/staging/solr/backup:/opt/backup

**Comment by makuk66** [comment]
@Mizar01 I tried your working example from https://github.com/docker-solr/docker-solr/issues/245#issuecomment-530361570, and that works fine:

```
issue-245» cat > docker-compose.yml <<EOM
 version: '2'
services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - ./home:/var/solr
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - testcore1
EOM
issue-245» mkdir home && sudo chown 8983:8983 home
issue-245» docker-compose up
```

but you don't need to change the docker-entrypoint, you can just specify the command:
```
issue-245» cat > docker-compose.yml <<EOM
version: '3'
services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - ./home:/var/solr
    command: solr-precreate testcore2
EOM
issue-245» sudo rm -fr home && mkdir home && sudo chown 8983:8983 home
issue-245» docker-compose up
```

@stefanocog In your example from https://github.com/docker-solr/docker-solr/issues/245#issuecomment-530318821
```
version: '3'
services:
  solr:
    image: solr:8.2.0
    ports:
      - "8983:8983"
    volumes:
      - ./cores:/var/solr
    entrypoint:
      - bash
      - "-c"
      - "precreate-core mycore; exec solr -f"
```
you're calling `precreate-core` and exec'ing solr, but you're never executing the parts of the normal scripts that create the directories for you. See https://github.com/docker-solr/docker-solr/blob/master/scripts/solr-precreate#L21 which calls `init-var-solr`. So just use solr-precreate as a I show above and all will be done for you. If for some other reason you really want to `precreate-core`+`exec solr -f`, make sure you run `init-var-solr` first.

> INIT_SOLR_HOME is no longer supported in 8+ versions.
> The docker documentation should mention that.

I'll add that.
