### ISSUE TITLE
Add a wait-for-zookeeper script

### ISSUE THREAD

**Issue by makuk66** [docker-solr/docker-solr#254]
The [solr helm chart in the incubator](https://github.com/helm/charts/tree/master/incubator/solr) has [this bit](https://github.com/helm/charts/blob/9eba7b1c80990233a68dce48f4a8fe0baf9b7fa5/incubator/solr/templates/statefulset.yaml#L60) where an init container is used to delay Solr starting until the ZooKeeper cluster is up, serving requests, and has elected a master. This did not work for me; it would never find a master, likely due to https://github.com/docker-library/busybox/issues/61#issuecomment-528926762%20about%20busybox. And having code in a helm chart is not ideal anyway. It would be ideal if there was such a script in the ZooKeeper image, but I'm not aware of one.

So it'd be useful to add one in docker-solr, so that you could do:

```
      initContainers:
        - name: check-zk
          image: solr:8.2
          command:
            - /opt/docker-solr/scripts/wait-for-zookeeper.sh
            - solr-zookeeper-headless
```

and then keep an eye on its progress with `kubectl logs solr-0 -c check-zk`.
