### ISSUE TITLE
Grab the IP at which Solr Server's container is running?

### ISSUE THREAD

**Issue by AdityaSoni19031997** [docker-solr/docker-solr#256]
Thanks for your repo!
Coming to my issue, Solr server generally runs on `localhost` but when i used docker compose in the way shown below, it's getting a separate container on it's own whose IP i figure out from the host's bash shell via `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solr_docker_compose` which varies always for me.. ;

My docker-compose file looks like
```
version: "3.7"
services:
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8000:5000"
        container_name: "my_app"
    solr_v2:
        image: solr:8.2.0
        container_name: "solr_docker_compose"
        volumes:
            - /Users/abc/Downloads/Archive/:/var/solr/data
        ports:
            - "8983:8983"
        links:
            - web
```

So how can i figure out the IP at which the container named `solr_docker_compose` is running at from the my_app container?

I have tried searching in the `ENV` variables of the `my_app` container but didn't find any as such as depicted in this SO [question](https://stackoverflow.com/questions/41279825/how-to-set-custom-ip-for-solr-server-from-docker-compose-file)

Thanks.
