### ISSUE TITLE
Issue with SolrCloud with examples

### ISSUE THREAD

**Issue by mahajanankur** [docker-solr/docker-solr#324]
I am trying to run the Solr in **SolrCloud mode with example** but getting an interactive argument issue while starting it. Is there any way to do so? If not this might be done through an argument as well.

I can run it without examples successfully by

`command: sh -c "solr start -c -f"`

Please find below my docker-compose file.

```
version: '3'
services:
  zookeeper:
    image: zookeeper:3.5
    container_name: zoo_solr
    restart: always
    ports:
      - ${ZOO_EXPOSED_PORT}:2181
    networks:
      - solr

  solr:
    image: solr:8.3
    container_name: solr
    ports:
      - ${SOLR_EXPOSED_PORT}:8983
    depends_on:
      - zookeeper
    environment:
      ZK_HOSTS: ${ZK_HOSTS}
      SOLR_JAVA_MEM: "-Xms2g -Xmx2g"
    volumes:
      - solr_data:/var/solr/
    command: sh -c "solr start -e cloud"
    networks:
      - solr

networks:
  solr:
    
volumes:
  solr_data:

```
![error](https://user-images.githubusercontent.com/7963490/85155385-52027800-b276-11ea-9848-79388563b887.png)
