### ISSUE TITLE
Sharing volume with host

### ISSUE THREAD

**Issue by stefanocog** [docker-solr/docker-solr#33]
I need share the solr data of my core with host, if i share in docker-compose like
```
volumes:
 - /opt/solr/mycore/data:/opt/solr/server/solr/mycore/data
```
I can't create the core `mycore` because i have problem of permission 
```
/opt/solr/bin/solr create -c mycore
ERROR: Error CREATEing SolrCore 'mycore': Unable to create core [mycore] Caused by: Can't find resource 'solrconfig.xml' in classpath or '/opt/solr/server/solr/mycore/conf'
```
there is a way to share data of core?

**Comment by makuk66** [comment]
If you try to just mount the data directory, then that will prevent Solr from creating the directory for the core. Then it fails, because you have not provided configuration. So you need to provide a configured core directory, owned by the solr user:

```
$ ls -ld mycore
drwxr-xr-x 4 8983 8983 4096 May 30 13:44 mycore

$ find .
./mycore/conf/stopwords.txt
./mycore/conf/solrconfig.xml
./mycore/conf/managed-schema
./mycore/conf/protwords.txt
./mycore/conf/_rest_managed.json
./mycore/conf/lang
./mycore/conf/lang/stopwords_en.txt
./mycore/conf/currency.xml
./mycore/conf/synonyms.txt
./mycore/core.properties
./mycore/data

$ docker run -v $PWD/mycore:/opt/solr/server/solr/mycore solr:6
```
Solr will then use that data directory.

But I would recommend this simpler way instead: mount a directory to hold all your cores, and then create one in it before Solr starts:

```
mkdir mycores
sudo chown 8983:8983 mycores
docker run -v $PWD/mycores:/opt/solr/server/solr/mycores solr:6 solr-precreate mycore
```

**Comment by mehaase** [comment]
This has been a problem for me, too. My goal is to have `docker-compose up` as the only step needed for a full-stack deployment of a web app with postgres, apache, solr, etc. This requires that I use Docker named volumes and there's no way to run other shell commands on the host prior to running the container. The shortest solution I can find is to run the container as root, e.g. `docker run -u root ...` or adding the `user: root` directive to docker compose.

@makuk66 A workaround is to `mkdir -p /opt/solr/server/solr/mycores` in the Dockerfile after `USER solr`. Then if a user mounts a volume at `/opt/solr/server/solr/mycores`, that volume inherits the `solr:solr` ownership. Thoughts?

**Comment by makuk66** [comment]
> A workaround is to mkdir -p /opt/solr/server/solr/mycores in the Dockerfile after USER solr. Then if a user mounts a volume at /opt/solr/server/solr/mycores, that volume inherits the solr:solr ownership

I see that suggestion in https://github.com/docker/docker/issues/2259#issuecomment-223162107.
This does work for me with named volumes, but not host-mounted volumes.

### Named volumes

With this Dockerfile patch:

```
diff --git a/6.0/Dockerfile b/6.0/Dockerfile
index a0dc875..f55ffca 100644
--- a/6.0/Dockerfile
+++ b/6.0/Dockerfile
@@ -31,7 +31,7 @@ RUN mkdir -p /opt/solr && \
   gpg --batch --verify /opt/solr.tgz.asc /opt/solr.tgz && \
   tar -C /opt/solr --extract --file /opt/solr.tgz --strip-components=1 && \
   rm /opt/solr.tgz* && \
-  mkdir -p /opt/solr/server/solr/lib && \
+  mkdir -p /opt/solr/server/solr/lib /opt/solr/server/solr/mycores && \
   sed -i -e 's/#SOLR_PORT=8983/SOLR_PORT=8983/' /opt/solr/bin/solr.in.sh && \
   sed -i -e '/-Dsolr.clustering.enabled=true/ a SOLR_OPTS="$SOLR_OPTS -Dsun.net.inetaddr.ttl=60 -Dsun.net.inetaddr.negative.ttl=60"' /opt/solr/bin/solr.in.sh && \
   chown -R $SOLR_USER:$SOLR_USER /opt/solr && \
```

and this `docker-compose.yml`:

```
version: '2'
services:
  
  solr:
    image: docker-solr/docker-solr:6
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore2
volumes:
  data:
```

`docker-compose up`, `docker-compose stop`, `docker-compose start` works.
Does that match your use-case?
If so, that seems like a nice thing to do.

Note that you can already do that today with an un-patched image, with a less elegant:

```
version: '2'
services:
  
  solr:
    image: solr:6
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    depends_on:
      - solrdata
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore1
  solrdata:
    image: solr:6
    volumes:
      - data:/opt/solr/server/solr/mycores
    user:
      root
    entrypoint:
      - chown
      - solr:solr
      - /opt/solr/server/solr/mycores
volumes:
  data:
```

### host-mounted volumes

So I have my directory owned by `solr`:

```
mak@cylon:~/docker-solr/docker-solr$ docker run docker-solr/docker-solr:6 ls -ld /opt/solr/server/solr/mycores
drwxr-xr-x 2 solr solr 4096 Jun  4 13:07 /opt/solr/server/solr/mycores
```

But when I have a local directory my user `mak` with uid 1000 in the host, and mount onto that location, that overrides it:

```
mak@cylon:~/docker-solr/issue33$ ls -ld mycores
drwxrwxr-x 2 mak mak 4096 Jun  4 13:47 mycores

mak@cylon:~/docker-solr/issue33$ ls -ldn mycores
drwxrwxr-x 2 1000 1000 4096 Jun  4 15:41 mycores

mak@cylon:~/docker-solr/issue33$ docker run -v $PWD/mycores:/opt/solr/server/solr/mycores docker-solr/docker-solr:6 ls -ld /opt/solr/server/solr/mycores
drwxrwxr-x 2 1000 1000 4096 Jun  4 14:41 /opt/solr/server/solr/mycores
````

and thus does not allow the core to be written by the `solr` user:

```
mak@cylon:~/docker-solr/issue33$ docker run -v $PWD/mycores:/opt/solr/server/solr/mycores docker-solr/docker-solr:6 solr-precreate mycore1
Executing solr-precreate command
cp: cannot create directory ‘/opt/solr/server/solr/mycores/mycore1’: Permission denied
```

I can't chown the `mycores` in the `docker-entrypoint.sh` either because by then we're running as `solr`.
I don't really see how to get around that other than staying root in the Dockerfile, chowning `mycores` in the entrypoint, and then dropping to `solr` privs with https://github.com/tianon/gosu to run solr. Which is worth considering, but feels perhaps a little heavy-handed.
