### ISSUE TITLE
Run multiple solr instances

### ISSUE THREAD

**Issue by Thaval** [docker-solr/docker-solr#384]
Hi,

I'd like to run two independent solr nodes, one for development and one for testing, so I added the following to my docker-compose yaml:
```
solrnode1:
    image: solr:8.7.0
    container_name: solrnode1
    ports:
      - "8981:8983"
    hostname: solrnode1
    environment:
      ZK_HOST: zookeeper1:2181
      SOLR_HEAP: 1g
    depends_on:
      - zookeeper1
    volumes:
      - solrdata1:/var/solr
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8983/solr/" ]
      interval: 10s
      timeout: 5s
      start_period: 15s

  solrnode2:
    image: solr:8.7.0
    container_name: solrnode2
    ports:
      - "8982:8984"
    hostname: solrnode2
    environment:
      ZK_HOST: zookeeper2:2182
      SOLR_HEAP: 1g
    depends_on:
      - zookeeper2
    volumes:
      - solrdata2:/var/solr
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8984/solr/" ]
      interval: 10s
      timeout: 5s
      start_period: 15s
```

Unfortunately, `docker-compose ps`  reveals that solrnode2 is unhealthy.  The logs for it says 
`Failed to connect to localhost port 8984: Connection refused`

Why is that and how can I solve it?

My goal is to have two solr instances that do not share anything, so they are completely independent and separated.

Edit: Solved it
