### ISSUE TITLE
Volumes mounted with root as owner

### ISSUE THREAD

**Issue by svenwltr** [docker-solr/docker-solr#50]
We are trying to use this image with Kubernetes. With this we have the problem, that we are only able to mount volumes with root as owner. This means solr isn't able to write to the volume, since it doesn't has the required permissions.

Is there a way to write to use this kind of volume with this image?

The only solution I see at the moment is to set `SOLR_USER` to root and build the image by ourselves.

---

In case you are interested in Kuberenetes manifest:

```yaml
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: solr
  labels:
    app: solr
spec:
  serviceName: solr
  replicas: 3
  template:
    metadata:
      name: solr
      labels:
        app: solr
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: solr
        image: solr:6-alpine
        ports:
        - name: http
          containerPort: 8983
        command:
        - /bin/bash
        args:
        - -c
        - /opt/solr/bin/solr start -f -z zookeeper:2181 -Dsolr.data.dir=/data
        volumeMounts:
        - name: datadir
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
```

**Comment by svenwltr** [comment]
We have found a way to change the user id. I'll leave this here in case somebody is interested in it:

```yaml
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: solr
  labels:
    app: solr
spec:
  serviceName: solr
  replicas: 2
  template:
    metadata:
      name: solr
      labels:
        app: solr
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
            {
                "name": "change-volume-owner",
                "image": "alpine:3.4",
                "imagePullPolicy": "IfNotPresent",
                "command": ["/bin/chown"],
                "args": ["8983:8983", "/datadir"],
                "volumeMounts": [
                    {
                        "name": "datadir",
                        "mountPath": "/datadir"
                    }
                ]
            }
        ]'
    spec:
      containers:
      - name: solr
        image: solr:6-alpine
        ports:
        - name: http
          containerPort: 8983
        command:
        - /bin/bash
        args:
        - -c
        - /opt/solr/bin/solr start -f -z zookeeper:2181 -Dsolr.data.dir=/data
        volumeMounts:
        - name: datadir
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
```
