### ISSUE TITLE
Solr and Zookeeper on Docker 1.12 Swarm 

### ISSUE THREAD

**Issue by viktorsmari** [docker-solr/docker-solr#52]
Will there be an updated example in the docs on how to use Solr and Zookeeper on 3 machines using Docker 1.12 Swarm?

**Comment by makuk66** [comment]
I started looking at that. For my local test cluster I've updated my custom ISO to use the current Ubuntu LTS, and updated my Fabric deployment scripts to install the new Swarm, so I'm ready to experiment. But it seems a lot has changed: [docker service](https://docs.docker.com/engine/reference/commandline/service_create/), [stacks](https://docs.docker.com/docker-cloud/apps/stacks/), the [routing mesh](https://blog.docker.com/2016/08/docker-online-meetup-41-deep-dive-docker-1-12-networking/). It's not immediately entirely clear to me how those map onto a recommended Solr cluster setup, especially one that reliably survives interleaved container stop/starts. I will get back to figuring this out a bit more, but no promises on timelines.

If anyone else comes across blogs/docs deploying ZooKeeper/Solr an the Docker 1.12 swarm, please add them to this issue.

**Comment by viktorsmari** [comment]
Great! 
I am trying this locally with 3 CoreOS machines running via vagrant and docker 1.12. I am able to spin up the containers easily but not sure how to connect them.

I let my local machine (ubuntu) be the Swarm leader via `docker swarm init` and then I let the 3 other CoreOS machines join.

Then I do these 2:
`docker service create --mode=global --name solr --p 8983:8983 solr:5.3.1`

`docker service create --mode global --name zook --p 2181:2181 -p 2888:2888 -p 3888:3888 jplock/zookeeper:3.4.8`

Now every CoreOS machine has solr running but I don't know how to interconnect them.

**Comment by viktorsmari** [comment]
Also, maybe I should not be using Zookeeper if Docker Swarm has all the same features?

**Comment by makuk66** [comment]
> Also, maybe I should not be using Zookeeper if Docker Swarm has all the same features?

Solr uses Zookeeper to store its own cluster state about what collections/shards are on which nodes. The new docker swarm mode has a similar raft consensus cluster, but Solr can't use that to store its own info. So you will still need ZooKeeper.

**Comment by risdenk** [comment]
@viktorsmari you were pretty close just some minor things. Here are the commands that I used that seem to work (I didn't try scaling up/down)

```
docker service create --mode global --name zook -p 2181:2181 -p 2888:2888 -p 3888:3888 jplock/zookeeper:3.4.8
docker service create --mode=global --name solr -p 8983:8983 solr:alpine -c -z zook
```

The items that I think tripped you up:
* using --p instead of just -p for a few arguments
* need to specify -c to start Solr in cloud mode
* need to specify -z and specify zookeeper nodes
** I used zook since that is the name of the Zookeeper service

**Comment by vincent221174** [comment]
If any care (regarding date of last commented)...

@risdenk you were also very near of the solution, but those commands but :

`docker network create --driver overlay  --opt encrypted  my-kwest-net`

... could achieve the point for me , before your both cmd , but modified with the network info,  could make  'zook' host known by solr container :  

`docker service create --network my-kwest-net --mode global --name zook -p 2181:2181 -p 2888:2888 -p 3888:3888 jplock/zookeeper:3.4.8`

`docker service create --network my-kwest-net  --mode=global --name solr -p 8983:8983 solr:alpine -c -z zook`


Whatever, thx for your work.

**Comment by Noodle05** [comment]
I don't think you are creating a zookeeper cluster by using command:
```
docker service create --network my-net --mode global --name zookeeper -p 2181:2181 -p 2888:2888 -p 3888:3888 zookeeper:3.4.9
```

In order to form a zookeeper cluster, each node need to have a unique number ID, and need to know all  zookeeper nodes in the cluster.

Your command will create zookeeper node on each docker node. However, they are individual zookeeper instance, not part of same cluster.

**Comment by si-harps** [comment]
Hi all, i'd like to chime in at this point as i'm working on a production docker/solr/zookeeper setup. Please see below for the docker-compose.yml file i'm using to create services as part of a swarm...

```
version: '3'
services:
    zoo-1:
        image: zookeeper
        ports:
            - 2181:2181
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo-2:2888:3888 server.3=zoo-3:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            replicas: 1
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm1]
    zoo-2:
        image: zookeeper
        ports:
            - 2182:2182
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 2
            ZOO_PORT: 2182
            ZOO_SERVERS: server.1=zoo-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo-3:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm2]
    zoo-3:
        image: zookeeper
        ports:
            - 2183:2183
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 3
            ZOO_PORT: 2183
            ZOO_SERVERS: server.1=zoo-1:2888:3888 server.2=zoo-2:2888:3888 server.3=0.0.0.0:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm3]
    solr:
        image: solr
        hostname: solr-{{.Node.ID}}
        # hostname: solr-{{.Node.ID}}
        ports:
            - 8983:8983
        networks:
            - zoonet
        volumes:
            - ./opt/solr/logs:/opt/logs
            - ./opt/solr/store:/store
            - ./opt/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            # SOLR_HOST: solr-{{.Node.ID}}
            SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            SOLR_LOGS_DIR: /opt/logs
        depends_on:
            - zoo-1
            - zoo-2
            - zoo-3
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - zoonet
networks:
    zoonet:
        driver: overlay
        ipam:
            driver: default
            config:
                - subnet: 10.101.0.0/16
```

...everything seems fine and dandy except when a container drops and restarts on a different IP. Is there any way i can remedy this?

Here are some options i have tried but hit dead-ends on...

- Creating individual solr services (eg. solr-1, solr-2, solr-3), replicating once on each node, then setting the SOLR_HOST environment variable to match. This allows each service to be discoverable by name but restricts me to using a different port for each (not great for a load balanced environment)
- Setting the hostname of each globally deployed solr service to a unique value (see 'hostname' property on docker-compose file above). This almost worked except that the hostname is not discoverable on the overlay network so node were unable to communicate with each other`
- Adding an Nginx round-robin load balancer to route requests to each of my Solr instances. Same issue in that a container IP change affected the routing.
- Tearing my hair out. This had obvious drawbacks to both my appearance and general comfort level. Didn't affect the deployment outcome in any way.

Does anyone have any other ideas or advice they could offer? Many thanks in advance.

**Comment by si-harps** [comment]
Following on from my previous comment. I've decided to go with the following template...

```
version: '3'
services:
    zoo-1:
        image: zookeeper
        ports:
            - "2181:2181"
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo-2:2888:3888 server.3=zoo-3:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            replicas: 1
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm1]
    zoo-2:
        image: zookeeper
        ports:
            - "2182:2182"
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 2
            ZOO_PORT: 2182
            ZOO_SERVERS: server.1=zoo-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo-3:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm2]
    zoo-3:
        image: zookeeper
        ports:
            - "2183:2183"
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 3
            ZOO_PORT: 2183
            ZOO_SERVERS: server.1=zoo-1:2888:3888 server.2=zoo-2:2888:3888 server.3=0.0.0.0:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm3]
    solr-1:
        image: solr
        ports:
            - 8983:8983
        networks:
            - zoonet
        volumes:
            - ./opt/solr/logs:/opt/logs
            - ./opt/solr/store:/store
            - ./opt/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            SOLR_LOGS_DIR: /opt/logs
            SOLR_HOST: solr-1
            SOLR_HEAP:
            SOLR_JAVA_MEM:
        depends_on:
            - zoo-1
            - zoo-2
            - zoo-3
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm1]
        command: 
            - "solr-foreground"
    solr-2:
        image: solr
        ports:
            - 8984:8983
        networks:
            - zoonet
        volumes:
            - ./opt/solr/logs:/opt/logs
            - ./opt/solr/store:/store
            - ./opt/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            SOLR_LOGS_DIR: /opt/logs
            SOLR_HOST: solr-2
            SOLR_HEAP:
            SOLR_JAVA_MEM:
        depends_on:
            - zoo-1
            - zoo-2
            - zoo-3
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm2]
        command: 
            - "solr-foreground"
    solr-3:
        image: solr
        ports:
            - 8985:8983
        networks:
            - zoonet
        volumes:
            - ./opt/solr/logs:/opt/logs
            - ./opt/solr/store:/store
            - ./opt/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            SOLR_LOGS_DIR: /opt/logs
            SOLR_HOST: solr-3
            SOLR_HEAP:
            SOLR_JAVA_MEM:
        depends_on:
            - zoo-1
            - zoo-2
            - zoo-3
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm3]
        command: 
            - "solr-foreground"
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - zoonet
networks:
    zoonet:
        driver: overlay
        ipam:
            driver: default
            config:
                - subnet: 10.101.0.0/16
```

Although starting each Solr instance as a separate service and replicating once across each node in the cluster seems to be a little clunky, in reality i achieves ideal results. Once deployed each instance is available on each of the exposed ports (even though i am only really interested in 8983) meaning i can round-robin the nodes via an AWS ELB. Does anyone see any potential issues with this?

**Comment by randyhoulahan** [comment]
@si-harps did you find a solution?

**Comment by lavdnone** [comment]
from the best of my understanding zookeeper exchanges data between solr while solr does indexing and services queries, like on this pic
https://sematext.com/wp-content/uploads/2016/12/SolrCloud-architecture.png

put static IPs on your containers and bridge network to the host - each service should have network assignment like below

```
      networks:
        zoonet:
          ipv4_address: 10.101.0.XXX
          aliases:
            - solr1

networks:
    zoonet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.101.0.0/16

```

that said why would you need all those containers in one docker-compose file?
you should get one Zoo and one Solr in it and start them on each server you have, specifying server IPs in ZOO_SERVERS: server.1=192.168.1.XX1:2888:3888 server.2=192.168.1.XX2:2888:3888 server.3=192.168.1.XX3:2888:3888
and external IPs for Solr ZK_HOST: 192.168.1.XX1:2181,192.168.1.XX2:2182,192.168.1.XX3:2183

then direct your clients round-robin or not to those server IPs 192.168.1.XX1-3

**Comment by sugun999** [comment]
@si-harps did you find a solution?

**Comment by Noodle05** [comment]
You don't need a static IP for each zookeeper node, just need specify net alias.

Also, you don't need give different port for each zookeeper node. Those port should only available inside overlay network.

Try something like this:

```
version: '3'
services:
    zoo-1:
        image: zookeeper
        networks:
            zoonet:
              aliases:
                - zk-1
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zk-1:2888:3888 server.2=zk-2:2888:3888 server.3=zk-3:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            replicas: 1
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm1]
    zoo-2:
        image: zookeeper
        networks:
            zoonet:
                aliases:
                    - zk2
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 2
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zk-1:2888:3888 server.2=zk-2:2888:3888 server.3=zk-3:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm2]
    zoo-3:
        image: zookeeper
        networks:
            zoonet:
                aliases:
                    - zk3
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 3
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zk-1:2888:3888 server.2=zk-2:2888:3888 server.3=zk-3:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm3]
    solr:
        image: solr
        hostname: solr-{{.Node.ID}}
        # hostname: solr-{{.Node.ID}}
        ports:
            - 8983:8983
        networks:
            - zoonet
        volumes:
            - ./opt/solr/logs:/opt/logs
            - ./opt/solr/store:/store
            - ./opt/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            # SOLR_HOST: solr-{{.Node.ID}}
            SOLR_HOME: /store/solr
            ZK_HOST: zk-1:2181,zk-2:2181,zk-3:2181
            SOLR_LOGS_DIR: /opt/logs
        depends_on:
            - zoo-1
            - zoo-2
            - zoo-3
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - zoonet
networks:
    zoonet:
        driver: overlay
        ipam:
            driver: default
            config:
                - subnet: 10.101.0.0/16
```

**Comment by mehdizj2000** [comment]
```
version: '3'
services:
  zoo-1:
    image: zookeeper
    networks:
      zoonet:
        aliases:
          - zk-1
    volumes:
      - 'zoo-1_data:/data'
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: 'server.1=zk-1:2888:3888 server.2=zk-2:2888:3888 server.3=zk-3:2888:3888'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == node1]
  zoo-2:
    image: zookeeper
    networks:
      zoonet:
        aliases:
          - zk-2
    volumes:
      - 'zoo-2_data:/data'
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: 'server.1=zk-1:2888:3888 server.2=zk-2:2888:3888 server.3=zk-3:2888:3888'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == node2]
  zoo-3:
    image: zookeeper
    networks:
      zoonet:
        aliases:
          - zk-3
    volumes:
      - 'zoo-3_data:/data'
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: 'server.1=zk-1:2888:3888 server.2=zk-2:2888:3888 server.3=zk-3:2888:3888'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == node3]
networks:
  zoonet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.101.0.0/16
volumes:
  zoo-1_data: null
  zoo-2_data: null
  zoo-3_data: null
```

I am using the above compose file and after deploy I see zookeeper instances cannot communicate and I get errors like this at console:



```
2019-03-26 02:12:00,408 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumPeer$QuorumServer@184] - Resolved hostname: zk-2 to address: zk-2/10.101.0.5,
2019-03-26 02:12:00,411 [myid:1] - WARN  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumCnxManager@584] - Cannot open channel to 3 at election address zk-3/10.101.0.8:3888,
java.net.ConnectException: Connection refused (Connection refused),
	at java.net.PlainSocketImpl.socketConnect(Native Method),
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350),
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206),
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188),
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392),
	at java.net.Socket.connect(Socket.java:589),
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:558),
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectAll(QuorumCnxManager.java:610),
	at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:838),
	at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:957),
2019-03-26 02:12:00,413 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumPeer$QuorumServer@184] - Resolved hostname: zk-3 to address: zk-3/10.101.0.8,
2019-03-26 02:12:00,413 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:FastLeaderElection@847] - Notification time out: 60000,
2019-03-26 02:13:00,417 [myid:1] - WARN  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumCnxManager@584] - Cannot open channel to 2 at election address zk-2/10.101.0.5:3888,
java.net.ConnectException: Connection refused (Connection refused),
	at java.net.PlainSocketImpl.socketConnect(Native Method),
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350),
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206),
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188),
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392),
	at java.net.Socket.connect(Socket.java:589),
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:558),
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectAll(QuorumCnxManager.java:610),
	at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:838),
	at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:957),
```

Also I can ping other nodes by internal, external and host name withing each zookeeper instance and also from each other VMs. I tried to follow @Noodle05 but no result. I am struggling with this for more than a day still no result.

What wrong I did with this?

**Comment by makuk66** [comment]
@mehdizj2000 ZooKeeper questions are probably best directed at the ZooKeeper project.

I tried your file with a `docker stack deploy --compose-file docker-compose.yml issue52` in the latest Docker 18.09.5 on Linux, with adjusted node names for my 3-node test cluster, and saw the same problem. I'm not immediately sure about what the problem is, but I imagine it's to do with the fact that the DNS resolution in Docker Swarm uses the VIP. If you look at https://hub.docker.com/_/zookeeper, its example specifies hostnames; and when I add them, it worked ok.
I'd make some other changes too:
- for consistency I'd just use the same names for the services
- you don't need to specify the network alias explicitly
- ZooKeeper 3.5 will be changing the config string format, see http://zookeeper.apache.org/doc/r3.5.3-beta/zookeeperReconfig.html, so I'd play safe and ping your image to 3.4.

All together, the following works for me:

```
version: '3'
services:
  zoo1:
    image: zookeeper:3.4
    hostname: zoo1
    networks:
      zoonet:
    volumes:
      - 'zoo1_data:/data'
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: 'server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == trinity10]
  zoo2:
    image: zookeeper:3.4
    hostname: zoo2
    networks:
      zoonet:
    volumes:
      - 'zoo2_data:/data'
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: 'server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == trinity20]
  zoo3:
    image: zookeeper:3.4
    hostname: zoo3
    networks:
      zoonet:
    volumes:
      - 'zoo3_data:/data'
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: 'server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == trinity30]
networks:
  zoonet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.101.0.0/16
volumes:
  zoo1_data: null
  zoo2_data: null
  zoo3_data: null
```
