### ISSUE TITLE
Hangs on "registering core" when using docker-compose

### ISSUE THREAD

**Issue by cguess** [docker-solr/docker-solr#65]
Using this setup:

```
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - ./.docker/solr_cores:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - test_core
```

with ```docker-compose run solr```

Result:
Hangs at 
```4580 INFO  (coreLoadExecutor-6-thread-1) [   x:test_core] o.a.s.c.CoreContainer registering core: test_core```

Environment:
macOS 10.12
Docker: Version 1.12.1-beta26.1 (build: 12100)
12c3e636425f8d73622261cdc0efed28f8202db7
docker-compose version 1.8.0, build f3628c7

I've reset the entirety of the Docker machine, rebooted my machine, recreated the folders etc. If I have multiple cores it only hangs after the second (or third, or fourth) core. Running it with ```--verbose``` offers nothing new. The image builds and runs perfectly using the straight ```docker``` commands though.
