### ISSUE TITLE
JDBC Libraries for Data Import Handler

### ISSUE THREAD

**Issue by jamiejackson** [docker-solr/docker-solr#67]
I'm still somewhat new to Docker, so you might find that parts of my question reflect some misunderstandings about Docker, in general.

I figure anybody who uses Data Import Handler with JDBC is going to go down a similar road:

I'd like to be able to:

* On `docker-compose up`, download the MariaDB driver from a specific URL, preferably only if it hasn't been downloaded already, and make it available to Solr.
* Do the above without an intermediate base image.

I tried jumping through some hoops to make this happen: I figured I'd have a directory on the host where downloaded assets like this are persisted, then have a volume mounted to that spot, then put a script (that does the conditional download) into /docker-entrypoint-initdb.d (which itself is a volume). All that almost worked, but it seems that my init script can't write to the assets folder (because only root can write there).

I could, of course, manually download the jar to the host box and share that volume, but wherever possible, I'd like to eliminate manual steps like this (so it's straightforward to `docker-compose up` on *any* docker host).

Do I just need to bite the bullet and have an intermediate image? Something like this?

```Dockerfile
FROM solr:5

ADD https://downloads.mariadb.com/enterprise/1prc-8jnh/connectors/java/connector-java-1.4.6/mariadb-java-client-1.4.6.jar /opt/solr/server/lib
```
The problems that (I think) I see:
* One extra moving part (the extra base image) as far as maintenance/management goes.
* ADD doesn't do anything smart to locally cache downloads, so they download on every build.

Any tips would be welcome.

**Comment by risdenk** [comment]
If you want this is be completed contained, then an intermediate image is probably your best bet.

Another option is to write a wrapper script (ie: `run.sh`) that is something like:

```
#!/usr/bin/env bash

MARIA_VERSION=1.4.6

wget -O mariadb-java-client.jar https://downloads.mariadb.com/enterprise/1prc-8jnh/connectors/java/connector-java-${MARIA_VERSION}/mariadb-java-client-${MARIA_VERSION}.jar

docker-compose up "$@"
```

`docker-compose.yml` could have the volume pointing to `marigadb-java-client.jar`.

This would still allow for one command after a clone of a repo. You could do some more interesting stuff with the `run.sh` script for caching if you want. You could even have docker-compose build an image after the wget.

**Comment by jamiejackson** [comment]
Thanks, I hadn't thought of a wrapper. I'll try that for a while and see what I think. (The intermediate image will be my backup plan.)

**Comment by jamiejackson** [comment]
Hmm, the wrapper idea would be good if I were running Docker right on Linux, but there's a portability problem: My laptop is Windows.  This complicates things, since, when running Docker commands through `docker-machine`, obviously Windows doesn't understand the bash wrapper. I also can't execute it directly in the Docker machine, since boot2docker doesn't even have `docker-compose`.

I still have the intermediate image backup plan, but do you know of any workarounds for the script idea? I think there's a way to use docker-compose events, but I haven't seen any documentation that I can relate to nor simple tutorials to try.

**Comment by risdenk** [comment]
@jamiejackson There is a docker-compose for Windows as part of Docker toolbox last I checked.

There isn't much about docker-compose events. Building the intermediate image with docker-compose is viable with the build tag in the docker-compose.yml file.

**Comment by jamiejackson** [comment]
I hadn't noticed the `build` feature of `docker-compose`--that's a gold nugget right there! It's working well:

`Dockerfile`
```go
FROM solr:5

ENV maria_version=1.4.6
ENV maria_jar_name=mariadb-java-client-${maria_version}.jar
ENV maria_url=https://code.mariadb.com/connectors/java/connector-java-${maria_version}/${maria_jar_name}
ENV lib_path=/opt/solr/server/lib

ADD ${maria_url} ${lib_path}

USER root
RUN ls -al ${lib_path} \
  && chmod a+r ${lib_path}/${maria_jar_name} \
  && chown solr:solr ${lib_path}/${maria_jar_name}
USER ${SOLR_USER}
```

`docker-compose.yml`
```yaml
version: '2'
services:

  solr-mariadb-baseimage:
    build: ./baseimage
    image: solr-mariadb-baseimage

  solr:
    image: solr-mariadb-baseimage
    container_name: solr_stage2
    depends_on:
      - solr-mariadb-baseimage
    ports:
     - "8983:8983"
    volumes:
      - /c/www/apps/hudexchange/solr/solr/ask_a_question:/opt/solr/server/solr/mycores/ask_a_question
      - /c/www/apps/hudexchange/solr/solr/grantee:/opt/solr/server/solr/mycores/grantee
      - /c/www/apps/hudexchange/solr/solr/resource_library:/opt/solr/server/solr/mycores/resource_library
      - /c/www/apps/hudexchange/solr/solr/ta_portal:/opt/solr/server/solr/mycores/ta_portal
    restart: unless-stopped
```

I also see that ADD does some magic to prevent re-downloading if the file hasn't changed, so that's a bonus.
