### ISSUE TITLE
Handling Environment Differences in Data Import Handler Data Sources

### ISSUE THREAD

**Issue by jamiejackson** [docker-solr/docker-solr#68]
As it stands, [I'm pulling in my cores via volumes](https://github.com/docker-solr/docker-solr/issues/67#issuecomment-249989120).

Since I'm in the process of upgrading a Solr 4 server, I'm used to specifying the data source as a JNDI reference in `data-config.xml`.

```xml
<dataSource jndiName="jdbc/mydsn" />
```

What was nice about that is that I could keep the same core config files and use them for any environment, because of that JNDI indirection: Dev server's data source had dev DB connection info, stage had stage's, etc., but all `data-config.xml` files didn't change among environments.

As far as I know, the modern way to configure `data-config.xml` is like this:

```xml
<dataSource
	driver="org.mariadb.jdbc.Driver"
	url="jdbc:mysql://myhost:3306/myschema"
	user="me"
	password="mypass"
/>
```

Is there still a way to achieve this indirection?

One idea is something like this:

```xml
<!-- custom properties -->
<dataSource
	driver="org.mariadb.jdbc.Driver"
	url="${dataimporter.datasource.url}"
	user="${dataimporter.datasource.user}"
	password="${dataimporter.datasource.password}"
/>
```
However, I'm unsure:
* Whether this is a decent way to do it.
* Where is a decent place to set the properties.

I might have this all sideways, and I might have some fundamental/foundational issues in my thinking, so any tips are welcome.

**Comment by steffkes** [comment]
> As far as I know, the modern way to configure `data-config.xml` is like this: …

where did you get this from? i'm hoping we're not suggesting that somewhere in the Solr Docs? The idea you've describe is perfectly fine - using variables that would be resolved from `core.properties` (for example) is the way i'm using since i've started with Solr.

**Comment by risdenk** [comment]
> Where is a decent place to set the properties.

I haven't tried this, but just an idea in case it helps. Those looks like regular Java properties so you should be able to do something like this:

```
```

**Comment by jamiejackson** [comment]
> > As far as I know, the modern way to configure data-config.xml is like this: …

> where did you get this from? i'm hoping we're not suggesting that somewhere in the Solr Docs? The idea you've describe is perfectly fine - using variables that would be resolved from core.properties (for example) is the way i'm using since i've started with Solr.

I googled `data import handler configuration` and got these as the first two hits:

* https://wiki.apache.org/solr/DataImportHandler#Full_Import_Example
* https://cwiki.apache.org/confluence/display/solr/Uploading+Structured+Data+Store+Data+with+the+Data+Import+Handler

They both seem to agree with each other.

Why, what's your technique, @steffkes?

**Comment by jamiejackson** [comment]
> I haven't tried this, but just an idea in case it helps. Those looks like regular Java properties so you should be able to do something like this...

Yup, they are regular properties.  Yesterday, I tried outputting `/* ${java.home} */` in one of the queries, and it resolved.

I'll try out the -a option, thanks!

**Comment by steffkes** [comment]
> They both seem to agree with each other.

Well, yeah - but they are not trying to suggest, that you have to do it _this way_ and not any other. Given that the docs are meant for starters too, we try to provide a simple way to get started with the topic in question - almost always, that's not the only way to get things done.

using `core.properties` might be one way, using java properties as Kevin pointed out another - it depends a bit on your needs. what can change per environment, what shouldn't and so on.

Hope that clarifies things a bit?

> Why, what's your technique, @steffkes?

Early on i've used `core.properties` to define things, because they did all i needed. nowadays i try to stick with environment variables, because it's often much easier to maintain them through different environments - although i have to said i don't have _the perfect setup_ at hand. i'm improving here and there along with the projects i'm involved with.

**Comment by jamiejackson** [comment]
> Well, yeah - but they are not trying to suggest, that you have to do it this way and not any other. Given that the docs are meant for starters too, we try to provide a simple way to get started with the topic in question - almost always, that's not the only way to get things done.

What I meant to highlight was the fact that using an externally defined JNDI resource is no longer kosher.

**Comment by jamiejackson** [comment]
Properties specified with `-a` worked out well.

Here's the (environment-specific override) configuration I ended up with:

```yml
version: '2'
services:

  solr:
    container_name: solr_stage2
    volumes:
      - /c/www/myproject_solr/deployment_root/cores/ask_a_question:/opt/solr/server/solr/mycores/ask_a_question
      - /c/www/myproject_solr/deployment_root/cores/grantee:/opt/solr/server/solr/mycores/grantee
      - /c/www/myproject_solr/deployment_root/cores/resource_library:/opt/solr/server/solr/mycores/resource_library
      - /c/www/myproject_solr/deployment_root/cores/ta_portal:/opt/solr/server/solr/mycores/ta_portal
      - /var/docker/solr_stage2/data:/opt/solr/data
    command: >
      -a "
      -Ddataimporter.datasource.driver=org.mariadb.jdbc.Driver
      -Ddataimporter.datasource.url=jdbc:mysql://myhost:3306/myproject_stage2
      -Ddataimporter.datasource.user=foouser
      -Ddataimporter.datasource.password=p4$$w0r6
      "
```
