### ISSUE TITLE
solr-precreate command fails: Permission denied

### ISSUE THREAD

**Issue by yonas** [docker-solr/docker-solr#79]
After running `docker-compose up -d` and `docker-compose ps`, I can see that Solr failed to start, having state `Exit 1`.

```
$ docker-compose logs solr
Attaching to savassearch_solr_1
solr_1     | Executing solr-precreate command
solr_1     | cp: can't create directory '/opt/solr/server/solr/mycores/main': Permission denied
```
### docker-compose.yml

```
...
  solr:
    image: solr:5.5-alpine
    volumes:
      - ./docker-runtime/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - main
    ports:
      - "8003:8983"
...
```
- docker-compose version 1.9.0-rc1, build 28788bd
- Ubuntu 16.10, Linux ubuntu1 4.8.0-26-generic #28-Ubuntu SMP Tue Oct 18 14:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yonas** [comment]
Running `chmod 777 docker-runtime/solr` seems to be a temporary solution.

**Comment by makuk66** [comment]
From https://github.com/docker-solr/docker-solr/blob/master/README.md
```
$ sudo chown 8983:8983 mycores
```
in your example, chown ./docker-runtime/solr.

**Comment by yonas** [comment]
@makuk66 Thanks! I tried that before, but got an error. It seems to have worked now :/

**Comment by kapilsdv** [comment]
Hi, I'm encountering the same issue in development using OS - Windows 10
This is the solr-image part of the docker-compose.yml (i'm using it in a rails application)
```

  solr-development:
    image: solr:latest
    ports:
      - "8983:8983"
    volumes:
      - ./solr/data:/opt/solr/server/solr/mycores
      - ./config/solr:/sunspotconfig
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - development
      - /sunspotconfig
```

The error for `docker-compose run solr-development`
```
Executing /opt/docker-solr/scripts/solr-precreate development /sunspotconfig
cp: cannot create directory '/opt/solr/server/solr/mycores/development': Permission denied
```
