### ISSUE TITLE
question about recent changes

### ISSUE THREAD

**Issue by roaldle** [docker-solr/docker-solr#97]
Hi,

1) Why did some versions got deleted?

2) core.properties isn't read anymore when using solr-precreate.
This is the compose file im using. I change the name of the core in the core.properties.
```
version: "2.0"

services:

 solr:
  image: solr:5.5
  ports:
   - "127.0.0.1:8983:8983"
  volumes:
   -  /var/docker/ca001/solr:/solrconf
  entrypoint:
   - docker-entrypoint.sh
   - solr-precreate
   - mycore
   - /solrconf
  restart: always
```
